I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 33, in script
    wuffeli "wrrrwrwroffof r"
Exception: Sayer 'wuffeli' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 33, in script
    wuffeli "wrrrwrwroffof r"
  File "C:\Users\Pelitaiteilija\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Pelitaiteilija\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'wuffeli' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
FGJ_2024 1.0
Fri Jan 26 22:17:07 2024
