I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/rpy/scenes/event_final_day.rpy", line 3, in script
    return
Exception: Could not find return label ('game/rpy/scenes/scene_selector.rpy', 1706359050, 5).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/rpy/scenes/event_final_day.rpy", line 3, in script
    return
  File "C:\Users\Pelitaiteilija\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1801, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\Pelitaiteilija\Downloads\renpy-8.1.3-sdk\renpy\execution.py", line 741, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label ('game/rpy/scenes/scene_selector.rpy', 1706359050, 5).

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
FGJ_2024 1.0
Sat Jan 27 14:47:54 2024
